version: '3.8'
services:
  identidock:
    build: . 
    ports:
      - "5000:5000"
    environment:
      ENV: DEV 
    volumes:
      - ./app:/app
    depends_on:
      - dnmonster
      - redis
    networks:
      - elk-net

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - elk-net

  redis:
    image: redis:3.0
    networks:
      - elk-net

networks:
  elk-net:
    external: true
    name: elk_elk-net
